name: Build

on:
  workflow_call:
    outputs:
      container_image:
        description: The built container image
        value: ${{ jobs.build_container.outputs.container_image }}
      container_tags:
        description: The tags for the built container image
        value: ${{ jobs.build_container.outputs.container_tags }}

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Install
        run: deno install --lock
      - name: Build
        working-directory: ./ui/web
        run: |
          deno task build
      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: ./ui/web/_fresh
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Install
        run: deno install --lock
      - name: Build
        run: |
          deno task build:tui:linux-x86
          deno task build:tui:linux-aarch64
          deno task build:gui:linux-x86
          deno task build:gui:linux-aarch64
      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            ./build/x86_64-unknown-linux-gnu/tui
            ./build/aarch64-unknown-linux-gnu/tui
            ./build/x86_64-unknown-linux-gnu/gui
            ./build/aarch64-unknown-linux-gnu/gui
  build_mac:
    name: Build Mac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Install
        run: deno install --lock
      - name: Build
        run: |
          deno task build:tui:mac-x86
          deno task build:tui:mac-aarch64
          deno task build:gui:mac-x86
          deno task build:gui:mac-aarch64
      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            ./build/x86_64-apple-darwin/tui
            ./build/aarch64-apple-darwin/tui
            ./build/x86_64-apple-darwin/gui
            ./build/aarch64-apple-darwin/gui
  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Install
        run: deno install --lock
      - name: Build
        run: |
          deno task build:tui:win
          deno task build:gui:win
      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            ./build/x86_64-pc-windows-msvc/tui
            ./build/x86_64-pc-windows-msvc/gui
  build_container:
    name: Build Container
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ steps.build.outputs.image }}
      container_tags: ${{ steps.build.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Install
        run: deno install --lock
      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          build-args: |
            GIT_REVISION=${{ github.sha }}
