name: Develop

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: verify
