name: Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: verify
  release:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/release.yml
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
