name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: verify
  release:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/release.yml
    needs: build
    with:
      container_image: ${{ needs.build.outputs.container_image }}
      container_tags: ${{ needs.build.outputs.container_tags }}
