name: "Tests"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: install
        run: deno install --lock
      - name: linting
        run: deno lint
      - name: formatting
        run: deno fmt --check
      - name: Run tests
        run: deno test
      - name: Build docs
        run: deno task build:docs
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: calmez-ghbot
          GIT_CONFIG_EMAIL: ghbot-noreply@calmez.net
