name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install
        run: deno install --lock
      - name: Build
        run: deno task build:all
      - name: Asset upload
        uses: python-semantic-release/publish-action@v9.21.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ github.ref }}
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          folder: docs
          clean: true
          single-commit: true
          git-config-name: calmez-ghbot
          git-config-email: ghbot-noreply@calmez.net
