name: Release

on:
  workflow_call:
    inputs:
      event_name:
        type: string
        default: "push"
        description: The name of the event triggering the release
      target_ref:
        type: string
        default: "refs/heads/main"
        description: The target git reference for the release

env:
  REGISTRY: ghcr.io

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: python-semantic-release/python-semantic-release@v10.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .semantic-release.json
          vcs_release: true
          commit: false
  release_mac:
    name: Release Mac
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Get Release by Tag
        id: get_release_by_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "${{ needs.create_release.outputs.tag }}";
            const release = await github.request(
              `/repos/${context.repo.owner}/${context.repo.repo}/releases/tags/${tag}`,
            );
            return release.data.upload_url;
          result-encoding: string
      - uses: actions/download-artifact@v5
        with:
          name: mac-build
          path: ./build
      - name: Upload release asset TUI MacOS ARM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/aarch64-apple-darwin/tui
          asset_name: oot-save-edit_tui_macos-apple-silicon
          asset_content_type: application/x-mach-binary
      - name: Upload release asset TUI MacOS Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/x86_64-apple-darwin/tui
          asset_name: oot-save-edit_tui_macos-intel
          asset_content_type: application/x-mach-binary
      - name: Upload release asset GUI MacOS ARM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/aarch64-apple-darwin/oot-save-edit_apple-silicon.app.zip
          asset_name: oot-save-edit_gui_macos-apple-silicon.app.zip
          asset_content_type: application/zip
      - name: Upload release asset GUI MacOS Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/x86_64-apple-darwin/oot-save-edit_intel.app.zip
          asset_name: oot-save-edit_gui_macos-intel.app.zip
          asset_content_type: application/zip
  release_linux:
    name: Release Linux
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Get Release by Tag
        id: get_release_by_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "${{ needs.create_release.outputs.tag }}";
            const release = await github.request(
              `/repos/${context.repo.owner}/${context.repo.repo}/releases/tags/${tag}`,
            );
            return release.data.upload_url;
          result-encoding: string
      - uses: actions/download-artifact@v5
        with:
          name: linux-build
          path: ./build
      - name: Upload release asset TUI Linux ARM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/aarch64-unknown-linux-gnu/tui
          asset_name: oot-save-edit_tui_linux-intel
          asset_content_type: application/x-pie-executable
      - name: Upload release asset TUI Linux Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/x86_64-unknown-linux-gnu/tui
          asset_name: oot-save-edit_tui_linux-arm
          asset_content_type: application/x-pie-executable
      - name: Upload release asset GUI Linux ARM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/aarch64-unknown-linux-gnu/gui
          asset_name: oot-save-edit_gui_linux-arm
          asset_content_type: application/x-pie-executable
      - name: Upload release asset GUI Linux Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/x86_64-unknown-linux-gnu/gui
          asset_name: oot-save-edit_gui_linux-intel
          asset_content_type: application/x-pie-executable
  release_windows:
    name: Release Windows
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Get Release by Tag
        id: get_release_by_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "${{ needs.create_release.outputs.tag }}";
            const release = await github.request(
              `/repos/${context.repo.owner}/${context.repo.repo}/releases/tags/${tag}`,
            );
            return release.data.upload_url;
          result-encoding: string
      - uses: actions/download-artifact@v5
        with:
          name: windows-build
          path: ./build
      - name: Upload release asset TUI Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/tui.exe
          asset_name: oot-save-edit_tui.exe
          asset_content_type: application/x-dosexec
      - name: Upload release asset GUI Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_by_tag.outputs.result }}
          asset_path: ./build/gui.exe
          asset_name: oot-save-edit_gui.exe
          asset_content_type: application/x-dosexec
  release_container:
    name: Release Container
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"
      - name: Install
        run: deno install --lock
      - name: Get Release by Tag
        id: get_release_by_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "${{ needs.create_release.outputs.tag }}";
            const release = await github.request(
              `/repos/${context.repo.owner}/${context.repo.repo}/releases/tags/${tag}`,
            );
            return release.data.upload_url;
          result-encoding: string
      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          build-args: |
            GIT_REVISION=${{ github.sha }}
      - name: Push Image to Registry
        id: push_container_image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }} ${{ needs.create_release.outputs.version }}
          registry: ${{ env.REGISTRY }}/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  docs:
    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install
        run: deno install --lock
      - name: Generate docs
        run: deno task build:docs
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          folder: docs
          clean: true
          single-commit: true
          git-config-name: calmez-ghbot
          git-config-email: ghbot-noreply@calmez.net
